### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../data/modelnet/train_files.txt'

### ISSUE THREAD

**Issue by 357998846** [hkust-vgd/shellnet#8]
2020-01-08 16:18:11.355997-Preparing datasets...
Traceback (most recent call last):
  File "train_val_cls.py", line 232, in <module>
    main()
  File "train_val_cls.py", line 52, in main
    [data_train, label_train] = provider.load_cls_files(setting.filelist)
  File "/home/gnss/桌面/shellnet-master/utils/provider.py", line 76, in load_cls_files
    for line in open(filelist):
FileNotFoundError: [Errno 2] No such file or directory: '../data/modelnet/train_files.txt'

**Comment by 357998846** [comment]
I download the dataset as follows,but there is still having a bug. 
cd data_conversions
python3 ./download_datasets.py -d modelnet
cd ..
python3 train_val_cls.py
